app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

factor_index:
    defaults: {_controller: AppBundle/Controller/Factor:index}
    path: /factor
    
factor_new:
    defaults: {_controller: AppBundle/Controller/Factor:new}
    path: /factor/nuevo
    
factor_edit:
    defaults: {_controller: AppBundle/Controller/Factor:edit}
    path: /factor/editar
    
factor_delete:
    defaults: {_controller: AppBundle/Controller/Factor:delete}
    path: /factor/eliminar
    
factor_show:
    defaults: {_controller: AppBundle/Controller/Factor:show}
    path: /factor/ver/{factor}
    
medicacion_index:
    defaults: {_controller: AppBundle/Controller/Medicacion:index}
    path: /medicacion
    
medicacion_new:
    defaults: {_controller: AppBundle/Controller/Medicacion:new}
    path: /medicacion/nueva
    
medicacion_edit:
    defaults: {_controller: AppBundle/Controller/Medicacion:edit}
    path: /medicacion/{id}/editar
    
medicacion_delete:
    defaults: {_controller: AppBundle/Controller/Medicacion:delete}
    path: /medicacion/{id}/eliminar
    
medicacion_show:
    defaults: {_controller: AppBundle/Controller/Medicacion:show}
    path: /medicacion/{id}