_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

factor_index:
    defaults: {_controller: AppBundle:Factor:index}
    path: /factor
    
factor_new:
    defaults: {_controller: AppBundle:Factor:new}
    path: /factor/nuevo
    
factor_edit:
    defaults: {_controller: AppBundle:Factor:edit}
    path: /factor/editar
    
factor_delete:
    defaults: {_controller: AppBundle:Factor:delete}
    path: /factor/eliminar
    
factor_show:
    defaults: {_controller: AppBundle:Factor:show}
    path: /factor/ver/{id}
    
medicacion_index:
    defaults: {_controller: AppBundle:Medicacion:index}
    path: /medicacion
    
medicacion_new:
    defaults: {_controller: AppBundle:Medicacion:new}
    path: /medicacion/nueva
    
medicacion_edit:
    defaults: {_controller: AppBundle:Medicacion:edit}
    path: /medicacion/{id}/editar
    
medicacion_delete:
    defaults: {_controller: AppBundle:Medicacion:delete}
    path: /medicacion/{id}/eliminar
    
medicacion_show:
    defaults: {_controller: AppBundle:Medicacion:show}
    path: /medicacion/{id}