# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:  ROLE_MEDICO
        ROLE_MEDICO: ROLE_USER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
                provider: fos_userbundle
                login_path: fos_user_security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: paciente_index
                always_use_default_target_path: true

            logout: true
            anonymous: true

    access_control:
        - { path: ^/$,            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registrarse,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,    role: IS_AUTHENTICATED_ANONYMOUSLY }
